#############################################################################
# Makefile for building: GLQTFixed
# Generated by qmake (2.01a) (Qt 4.8.0) on: Sun Jan 1 02:47:38 2012
# Project:  GLQTFixed.pro
# Template: app
# Command: /home/Qt/qt-everywhere-opensource-src-4.8.0/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile GLQTFixed.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.0/include/QtCore -I/usr/local/Trolltech/Qt-4.8.0/include/QtGui -I/usr/local/Trolltech/Qt-4.8.0/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.8.0/include -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.0/lib -L/usr/X11R6/lib -lGLEW -lGLU -lQtOpenGL -L/usr/local/Trolltech/Qt-4.8.0/lib -L/usr/X11R6/lib -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/Qt/qt-everywhere-opensource-src-4.8.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/declarative_debug.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf \
		GLQTFixed.pro
QMAKE_TARGET  = GLQTFixed
DESTDIR       = 
TARGET        = GLQTFixed

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: GLQTFixed.pro  /usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/declarative_debug.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtOpenGL.prl \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.0/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile GLQTFixed.pro
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/declarative_debug.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/opengl.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.0/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtOpenGL.prl:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.0/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile GLQTFixed.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GLQTFixed1.0.0 || $(MKDIR) .tmp/GLQTFixed1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GLQTFixed1.0.0/ && $(COPY_FILE) --parents mainwindow.h .tmp/GLQTFixed1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/GLQTFixed1.0.0/ && (cd `dirname .tmp/GLQTFixed1.0.0` && $(TAR) GLQTFixed1.0.0.tar GLQTFixed1.0.0 && $(COMPRESS) GLQTFixed1.0.0.tar) && $(MOVE) `dirname .tmp/GLQTFixed1.0.0`/GLQTFixed1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GLQTFixed1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/local/Trolltech/Qt-4.8.0/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

